### Get the currently signed in user
GET http://localhost:9000/tasks

### Add task
POST http://localhost:9000/tasks
Content-Type: application/json

{
    "title": "Task 3",
    "description": "Task 3 description"
}