### POST Create a user
POST http://localhost:4200/user/signup
content-type: application/json

{
    "username": "user 3",
    "password": "password"
}

### POST Sign in user
POST http://localhost:4200/user/signin
content-type: application/json

{
    "username": "user 3",
    "password": "password"
}