### POST Create new task
POST http://localhost:4200/tasks
content-type: application/json

{
    "title": "Task 3",
    "description": "Task 3 description",
    "userId": "67352cebe41824ee695c57cf"
}

### GET Get all tasks for user
GET http://localhost:4200/tasks/67352cebe41824ee695c57cf
